/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.dnd.DirectorTransferable;
import hr.algebra.model.Actor;
import hr.algebra.model.Director;
import hr.algebra.model.Movie;
import hr.algebra.model.MovieDirectorRelationship;
import hr.algebra.model.User;
import hr.algebra.tableModel.MovieDirectorTableModel;
import hr.algebra.utilities.IconUtils;
import hr.algebra.utilities.MessageUtils;
import java.awt.datatransfer.Transferable;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.TransferHandler;

/**
 *
 * @author wExzEk
 */
public class CRUDMovieDirectorRelationtionship extends javax.swing.JPanel {

    /**
     * Creates new form CRUDMovieDirectorRelationtionship
     */
    private Repository repository;

    private Movie selectedMovie;

    private MovieDirectorTableModel movieDirectorTableModel;

    private MovieDirectorRelationship selectedMovieDirector;

    private DefaultListModel<Director> directorModel;

    private final Set<Director> directors = new TreeSet<>();

    public CRUDMovieDirectorRelationtionship(User user) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsDirector = new javax.swing.JList<>();
        lbIcon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsAvailableDirectors = new javax.swing.JList<>();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovieDirectors = new javax.swing.JTable();
        tfMovie = new javax.swing.JTextField();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel4.setText("Director");

        jScrollPane2.setViewportView(lsDirector);

        jScrollPane3.setViewportView(lsAvailableDirectors);

        btnDelete.setBackground(new java.awt.Color(204, 0, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("All directors");

        jLabel1.setText("Movie");

        tbMovieDirectors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMovieDirectors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMovieDirectorsMouseClicked(evt);
            }
        });
        tbMovieDirectors.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbMovieDirectorsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbMovieDirectors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGap(28, 28, 28)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(41, 41, 41)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        selectedMovie.getId();
        if (selectedMovie != null) {
            int movieId = selectedMovie.getId();
            try {
                repository.deleteMovieDirectorRelationship(movieId);
                MessageUtils.showInformationMessage("Delete Successful", "Actors deleted from the movie successfully.");
                showDirectors(movieId);
                showAllDirectors();
            } catch (Exception ex) {
                Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Delete Error", "Error occurred while deleting the actor from the movie.");
            }
        } else {
            MessageUtils.showInformationMessage("Selection Required", "Please select a movie actor relationship to delete.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbMovieDirectorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMovieDirectorsMouseClicked
        selectMovieDirector();
    }//GEN-LAST:event_tbMovieDirectorsMouseClicked

    private void tbMovieDirectorsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMovieDirectorsKeyPressed
        selectMovieDirector();
    }//GEN-LAST:event_tbMovieDirectorsKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JList<Director> lsAvailableDirectors;
    private javax.swing.JList<Director> lsDirector;
    private javax.swing.JTable tbMovieDirectors;
    private javax.swing.JTextField tfMovie;
    // End of variables declaration//GEN-END:variables

    private void showDirectors(int movieId) {
        try {
            directorModel = new DefaultListModel<>();
            List<Director> directors = repository.getDirectorsForMovie(movieId);
            for (Director director : directors) {
                directorModel.addElement(director);
            }
            lsDirector.setModel(directorModel);
        } catch (Exception ex) {
            Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showAllDirectors() {
        try {
            directorModel = new DefaultListModel<>();
            List<Director> allDirectors = repository.selectDirectors();

            allDirectors.stream()
                    .filter(actor -> !directors.contains(actor))
                    .forEach(directorModel::addElement);

            lsAvailableDirectors.setModel(directorModel);
        } catch (Exception ex) {
            Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void selectMovieDirector() {
        clearForm();
        int selectedRow = tbMovieDirectors.getSelectedRow();
        int rowIndex = tbMovieDirectors.convertRowIndexToModel(selectedRow);

        int movieId = (int) movieDirectorTableModel.getValueAt(rowIndex, 0);

        try {
            Optional<Movie> optMovie = repository.selectMovie(movieId);
            if (optMovie.isPresent()) {
                fillForm(optMovie.get());
            }
        } catch (Exception ex) {
            Logger.getLogger(CRUDMovies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void init() {
        try {
            initRepository();
            initTable();
            initDragNDrop();
        } catch (Exception ex) {
            Logger.getLogger(CRUDMovies.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void initRepository() {
        repository = RepositoryFactory.getRepository();
    }

    private void initTable() {
        tbMovieDirectors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbMovieDirectors.setAutoCreateRowSorter(true);
        tbMovieDirectors.setRowHeight(25);

        try {
            movieDirectorTableModel = new MovieDirectorTableModel(repository.selectMovies());
        } catch (Exception ex) {
            Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbMovieDirectors.setModel(movieDirectorTableModel);
    }

    private void initDragNDrop() {
        lsAvailableDirectors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsAvailableDirectors.setDragEnabled(true);
        lsAvailableDirectors.setTransferHandler(new ExportHandler());

        lsDirector.setDropMode(DropMode.ON);
        lsDirector.setTransferHandler(new ImportHandler());
    }

    private void clearForm() {
        selectedMovieDirector = null;
        selectedMovie = null;
    }

    private void fillForm(Movie movie) {
        selectedMovie = movie;
        tfMovie.setText(movie.getTitle());
        if (movie.getPicturePath() != null && Files.exists(Paths.get(movie.getPicturePath()))) {
            setIcon(lbIcon, new File(movie.getPicturePath()));
        }
        showDirectors(movie.getId());
        showAllDirectors();
    }

    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(CRUDMovies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private class ExportHandler extends TransferHandler {

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;
        }

        @Override
        protected Transferable createTransferable(JComponent c) {
            return new DirectorTransferable(lsAvailableDirectors.getSelectedValue());
        }
    }

    private class ImportHandler extends TransferHandler {

        @Override
        public boolean canImport(TransferSupport support) {
            return support.isDataFlavorSupported(DirectorTransferable.DIRECTOR_FLAVOR);
        }

        @Override
        public boolean importData(TransferSupport support) {
            Transferable transferable = support.getTransferable();

            try {
                Director director = (Director) transferable.getTransferData(DirectorTransferable.DIRECTOR_FLAVOR);

                if (isDirectorInList(director, lsDirector.getModel())) {
                    MessageUtils.showErrorMessage("Duplicate Actor", "Actor with the same name already exists in the list.");
                    return false;
                }

                if (directors.add(director)) {
                    loadDirectorsModel();
                    updateDatabase();
                    directors.clear();
                    return true;
                }
            } catch (Exception ex) {
                Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
            }
            return false;
        }

        private boolean isDirectorInList(Director director, ListModel<Director> model) {
            for (int i = 0; i < model.getSize(); i++) {
                Director existingDirector = model.getElementAt(i);
                if (existingDirector.getFullName().equals(director.getFullName())) {
                    return true;
                }
            }
            return false;
        }

        private void loadDirectorsModel() {
            try {
                directorModel = new DefaultListModel<>();
                List<Director> allDirectors = repository.selectDirectors();

                allDirectors.stream()
                        .filter(actor -> !directors.contains(actor))
                        .forEach(directorModel::addElement);

                lsDirector.setModel(directorModel);
                lsAvailableDirectors.setModel(directorModel);
            } catch (Exception ex) {
                Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        private void updateDatabase() {
            try {
                int movieId = selectedMovie.getId();

                for (Director director : directors) {
                    int directorId = director.getId();
                    repository.addDirectorToMovie(movieId, directorId);
                }

                showDirectors(movieId);

            } catch (Exception ex) {
                Logger.getLogger(CRUDMovieActorRelationship.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
